### PR TITLE
GitHub Actions config

### PR DESCRIPTION
**Pull request by sdarwin**
GitHub Actions CI script, generated from the .travis.yml file. Please refer to https://github.com/CPPAlliance/githubactions for more information and instructions.

### CODE REVIEW

**Comment by badair** [comment]
Thanks for the PR, will play around with this and potentially merge after 1.77.

**Comment by sdarwin** [comment]
@badair , sounds good.

This PR is slightly out-of-date.  Tomorrow I will try to send a newer one.

**Comment by sdarwin** [comment]
Updated ci.yml file in this PR.

**Comment by badair** [comment]
Works great, thanks. I cherry-picked to develop branch and will get it to master after the freeze is over.

**Pull request closed without merging**
