### PR TITLE
Fix for using callable_traits as a CMake dependency in other boost projects

### PR DESCRIPTION
**Pull request by HDembinski**
This fixes the problems described in #182.

### CODE REVIEW

**Comment by HDembinski** [comment]
Ping, could this PR please be merged? Thank you :)

**Comment by HDembinski** [comment]
Hi again, what is the show stopper for this PR?

Sorry, it is a large patch. Most is just renaming things so that it is consistent with boost.core and other boost lbraries. If you don't like the renaming of CMake variables, I can revert that and only make the changes that are visible to other projects.

What really matters are two lines:
https://github.com/boostorg/callable_traits/pull/183/files#diff-af3b638bc2a3e6c650974192a53c7291R61
and
https://github.com/boostorg/callable_traits/pull/183/files#diff-af3b638bc2a3e6c650974192a53c7291R67

The first one puts the common Boost:: prefix in front of the library name. This is making `callable_traits` consistent with the other boost libraries and avoids conflicts with any possible forks of `callable_traits`. The second line is very important. If this is not there, any project which includes `callable_traits` (like Boost.Histogram) fails.

**Comment by badair** [comment]
Merged, sorry for the severe delay.

**Comment by HDembinski** [comment]
Thanks!

**Pull request merged**
